"""empty message

Revision ID: 60ca2d3b498a
Revises: 
Create Date: 2025-08-27 22:10:51.848066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ca2d3b498a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('bid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('btitle', sa.String(length=64), nullable=False),
    sa.Column('blink', sa.Text(), nullable=False),
    sa.Column('bdate_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('notes',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ntitle', sa.String(length=64), nullable=False),
    sa.Column('ncontent', sa.Text(), nullable=False),
    sa.Column('ndate_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('tasks',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tcontent', sa.String(length=64), nullable=False),
    sa.Column('tdate_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    op.drop_table('notes')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
