"""empty message

Revision ID: c6978d3bc92f
Revises: 
Create Date: 2025-09-02 17:35:39.587031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6978d3bc92f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bookmarks',
    sa.Column('bid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('btitle', sa.String(length=64), nullable=False),
    sa.Column('blink', sa.Text(), nullable=False),
    sa.Column('bdate_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.uid'], ),
    sa.PrimaryKeyConstraint('bid')
    )
    op.create_table('notes',
    sa.Column('nid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ntitle', sa.String(length=64), nullable=False),
    sa.Column('ncontent', sa.Text(), nullable=False),
    sa.Column('ndate_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.uid'], ),
    sa.PrimaryKeyConstraint('nid')
    )
    op.create_table('tasks',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tcontent', sa.String(length=64), nullable=False),
    sa.Column('tdate_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.uid'], ),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('notes')
    op.drop_table('bookmarks')
    op.drop_table('Users')
    # ### end Alembic commands ###
